services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ny_taxi 
    volumes:
      - "dtc_postgres_volume_local:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:  
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"

volumes:
  dtc_postgres_volume_local:
    external: true

# To create the local docker volume run the below code
# docker volume create --name dtc_postgres_volume_local -d local 
